version: '1'
services:
  authentication:
    image: Authentication/authentication
    ports:
    - 8081:8081
  mongodb:
    image: mongo
    ports:
    - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  webApplication:
    image: webApplication